### ISSUE TITLE
Load / Save bug!

### ISSUE THREAD

**Issue by PatchByte** [otto-link/Hesiod#118]
Basically its saving / loading the same file even if you are choosing a new one!
For loading I fixed it by commenting the line: 
https://github.com/otto-link/Hesiod/blob/115d912faeb2a53175ca462f5eef48383689a4fc/Hesiod/src/nodes/view_tree/render_node_editor.cpp#L91

The same could probably fixed for saving:
https://github.com/otto-link/Hesiod/blob/115d912faeb2a53175ca462f5eef48383689a4fc/Hesiod/src/nodes/view_tree/render_node_editor.cpp#L124

**Comment by otto-link** [comment]
That's not very convenient... I'll look into it, thanks for the feedback

**Comment by otto-link** [comment]
- that's a bit odd, works fine with me but I moved the file dialog config declaration: d5f52c0 (available on branch `dev` only)
- `config.fileName = this->json_filename;` is used to set the default value of the filename in the dialog
- could you check if it fixes your issue?

**Comment by otto-link** [comment]
Finally found it: logical error... the file was saved at each frame :sweat_smile:
